import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from "next/link";
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Meteo from '@/components/weather'
import CompteurDeVues from '@/components/counter';
import Navigation from '@/components/navbar';


export default function Home() {
  const [date] = useState(new Date());
  const options = { day: 'numeric', month: 'long', year: 'numeric', weekday: 'long' };
  const dateString = date.toLocaleDateString('fr-FR', options);



    return (
    <>
      <Head>
        <title>Robin Pautigny</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <main className={styles.main}>
      <Navigation/>
      <div className={styles.body}>
        <div className={styles.rowMe}>
          <h1><span>Robin Pautigny</span></h1>
          <div className={styles.profilePicture}></div>
        </div>
        
      </div>
      <div className={styles.tag}>
        <div className={styles.tag1}>
          <span className={styles.tagText}>Creative entrepreneur</span>
        </div>
        <div className={styles.tag2}>
        <span className={styles.tagText}>{dateString}</span>
        </div>
        <div className={styles.tag3}>
        <span className={styles.tagText}>portfolio</span>
        </div>
      </div>
      
      <div className={styles.grid}>
            <div className={styles.grid1} >
            <div className={styles.section}>
              <div className={styles.last}>LATEST POST</div>
              <Link className={styles.seeMore} href="/Papernest">
                 <div className={styles.arrow}></div>                 
              </Link>
              </div>
            <div className={styles.pictureCard}></div>
            <div className={styles.titleCard}>
              <span>Become a product manager @ Papernest</span>
              <span><CompteurDeVues/></span>
            </div>
            <div className={styles.line}></div>
            <p className={styles.description}>While waiting for my first day at <span className={styles.bold}><a href="https://papernest.com" target='_blank' >Papernest</a></span> I wanted to start learning this trade.. .</p>
          </div>
        <div className={styles.grid2}>
          <Meteo/>
        </div>
        <div className={styles.grid3}></div>
      </div>
      </main>
    </>
    
  )}